sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: obGqPqfz+YUdUkjE5eufW/vnyOvNx5Un72uoDZAcngewdQBx8Drjt5tcXL20k/xfnrES+FomNNyaWkuerMmKh7fk80axUjtI4u8znokVw590INu+GYvyLAEMUWCv9m3vKGdjlgRWtYOHuLH2fbgEQm7OIVoTZjfX8bXnUFRISSHF6qpFr31aUh/OkaIH9w89RN1QmdOD5WnAHLPiwa33XB1PEx46BgTPjaQOGiZG3bcS0bCWszq7JC0cwcXpZhGL+aN96hKCFK37JGMWK9RN0NGv5rCroFA3u9Hj9xldUpfW39nmZ8/NmYcCOsU3t3XutTG85IDsXoPMFFVOxU9ZMAaIwO9thokTmRdtCZ+UaSIMj3pXKRmfYQv7u5PV7PZxt9J5jbF2hW92GslcpPu4FX40gUosmYJhMCLO3fnC3ziospi9t4piMM9IKH6d5azE2SImcbplsuj1/rQiTq5Bsg50YrGHdofQmuE+gzgwFYj8/yfvPQzAOW04P9GhbyT2KCSssuByfPfp/uE5fZZ3QsprK6KO7obB7vhk+ndEP8uqOLr1dOPWA+Fwkm7dF/xhZ4CeXQ6EU2Z6d8t4pcR6ME20xPrjDNWMgNqoZj+u3EWGcXkDZl1/sLASlH/4HDmMHEBF6UUrATalQdgU83vgb/00W1n+eMdatcpi1VFchMo=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: WEnwwn6Hpllo09hUjnobwt5Cm959bA3H+wacuVxTPucXWRo7hxks04nHMHFFRJs38LLpBRHblEr04wV/xKFjljIi1PEH+7zjCZeWcSo+hMYkSv0cnOThtcygTR1mpF20vAb0fNjqWfrBBbIv+X9ke6o8UPp+yci/iFqMWI69scwV6tIXyt9XhTl2hhi1qK9CMJBP9OCXpVQRFMkt6zhnifRblx3CBM9TBP3Eu4ee1hFcUmaSqAdbwG/u6rZAwR82xxljec4kYY4KYhyb9KN6nGkrap0FQR8DQUZ2fxEJLup+jHvjrDxYDpgW6LTEGloSntS70fkT4nKGZydH4w/6HuNinLZy7Nxf6d7pl1S0kyywUd0eM4WnRdwHOvob+LYumQ264YfTcg/LDSOOxH0D8+Vdq9zITql1by2vOo/a//3QrhBICi1paH5tLDTRTuetu3qiXAfOxvyS2lCE17OyNSzSrS/eRzDOFE5DqQC4IDAvQdw2AVz9Q+/cNdHOXYzpD9W2f/M1QMDOpjD1dJK5OS8enz/7q3yX989GCSs4tE+0PfpOQyOa22RYWWbFbKrvenbn9OO/biZ1w1rLsEge61mtbpC8SKcJvEYrGo/qS7GSQDgybQksg5ejSvsgUE8aLSqe2XubA8EmE3KzvmYtpso1HIRp3C/i41wvzxIP2Bo=
